### ISSUE TITLE
Current Bastion example doesn't compile

### ISSUE THREAD

**Issue by tuxiqae** [bastion-rs/bastion-rs.github.io#19]
So as the title says the current Bastion example on https://bastion.rs doesn't compile.

I would advise choosing either of the following:
- Fix the issue so the code compiles.
- Rewrite the example to be compatible with the Fort example - that way newcomers will be able to better compare between the two flavors and understand what's right for them. -- Rewriting it will be best if paired with a more complex code than the current Fort example.

**Comment by o0Ignition0o** [comment]
Wow I cant believe this issue totally went under the radar, I'm super sorry :(

I think we wanna go with the first option, or maybe do both so people get a better feel for it. It will probably match well with the (not so anymore) new distributor api and messagehandler!
