### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by hardliner66** [bastion-rs/bastion-rs.github.io#20]
I wanted to check out the webpage, but it's unreachable. Seems like there is a DNS problem.

**Comment by o0Ignition0o** [comment]
Hey Steve, thanks for letting us know!

It is indeed a dns renew issue, lemme check what i can do about it!

**Comment by hardliner66** [comment]
@o0Ignition0o Hi, it seems it still doesn't work. If you want I can temporarily set up a subdomain for bastion until this is fixed. So that people can at least reach it somewhere. I would just need a public IP for that. Wont be as pretty as bastion.rs, but better than being unreachable.

**Comment by o0Ignition0o** [comment]
Hey There!

We have been able to set up bastion-rs.com http://blog.bastion-rs.com/ for example, but we still have an issue getting the website back up, the code is living in this repository but there's something I'm not quite understanding about our CI/CD/Pages pipeline.

I'd love to talk this through with you if you happen to have any idea as to why http://bastion-rs.com/ doesn't  point us to the website :D

**Comment by hardliner66** [comment]
Does the blog and website run on the same host/ip?

**Comment by o0Ignition0o** [comment]
Both are hosted under github pages, although the CNAME entry varies. Redirection seems to work, but the pages generation mechanism seems to be askew.

we are using the CNAME method explained [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages)

**Comment by hardliner66** [comment]
Hmm, strange. I tried running it locally but, the build failed. I'm more of a backed guy, so I'm not sure what the problem could be. Does the static generation run in CI? If yes, does anything fail there?

**Comment by o0Ignition0o** [comment]
No worries ^^ I'll try to give it a spin locally as soon as I have a bit of time, I suspect it will work again as soon as It builds locally :)

**Comment by o0Ignition0o** [comment]
Ok http://www.bastion-rs.com/ seems to progressively get back online, through #21 and #22, and if this works out, we're only 1 step away from enforcing https!

This is close to be done, thanks a lot for opening the issue! 🎉

**Comment by hardliner66** [comment]
Thats pretty good progress. Site seems to work right now. Thanks for your time. :)

**Comment by hardliner66** [comment]
Will bastion-rs.com be the new domain or will the old domain be revived as well?

**Comment by o0Ignition0o** [comment]
AFAIK we're trying to get it back, so I can't tell for sure 😅

**Comment by hardliner66** [comment]
Ah okay. Because currently the alternative site works, but redirects to the wrong blog for instance.

**Comment by o0Ignition0o** [comment]
you mean http://blog.bastion-rs.com/ ?

**Comment by o0Ignition0o** [comment]
indeed! I'll open issues about that

**Comment by hardliner66** [comment]
Yeah. But depending on if and when the domain comes back, this might be a non-issue.

**Comment by o0Ignition0o** [comment]
I've opened https://github.com/bastion-rs/blog/issues/24 and https://github.com/bastion-rs/book/issues/12 so we can track it, and possibly revert eventually! thank for catching this 😁

**Comment by o0Ignition0o** [comment]
Ok we're now good to go, closing this! 🎉
