### ISSUE TITLE
www.bastion-rs.com shows error 404

### ISSUE THREAD

**Issue by hardliner66** [bastion-rs/bastion-rs.github.io#25]
I wanted to check if the blog links are now correct, but it seemed like the link didn't change. So I cleared my cache, now I get an error 404 when trying to reach https://www.bastion-rs.com/.

[bastion-rs.github.io](https://bastion-rs.github.io/) works tho. There might be some miss configuration still.

P.S.: It might make sense to get https://bastion-rs.com/ (without www) to work as well, or at least redirect to the www version.

**Comment by o0Ignition0o** [comment]
Oh The configuration blew up :( looking!

**Comment by o0Ignition0o** [comment]
Ok this should be working, but I'm wary of the various layers of cache on my machines.

@hardliner66 can you give it an other try and let me know?  ^^

**Comment by hardliner66** [comment]
@o0Ignition0o Perfect, it works now.
