### ISSUE TITLE
Blog for the site

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/bastion-rs.github.io#6]
Having a tech blog would be nice.

@azastrael @JohnTitor  wdyt?

**Comment by vertexclique** [comment]
@JohnTitor Yuki, do you have time for looking at that?

**Comment by JohnTitor** [comment]
I think it's good to create a new repository on bastion-rs, then put the blog there. And we should find a new template to make things easy as I mentioned before.

**Comment by o0Ignition0o** [comment]
Hey everyone :) 
FYI I've created a rustlang blog boilerplate which is part of the [rust community organization](https://github.com/rust-community/rust-lang-blog-boilerplate).

Although not quite up to date, maybe it can be forked here and restyled a bit, to serve as a base for a cool bastion blog ?

Edit: Just saw that you have merged the last PR on the boilerplate, so you're probably well aware of the repo ^^'

**Comment by JohnTitor** [comment]
Heh, indeed I know. It sounds good to me, any thoughts? @vertexclique

**Comment by o0Ignition0o** [comment]
https://github.com/bastion-rs/blog is being setup. (it's a fork from the boilerplate). We're a few DNS entries away from having something correct :)

**Comment by vertexclique** [comment]
We can close this. It is done and dusted! Thanks!
